### ISSUE TITLE
FR: Downloads location variable

### ISSUE THREAD

**Issue by DennisLfromGA** [WesBosch/brunch-toolkit#1]
I *know* this is a *big* ask but would there be a chance to make '`~/Downloads`' a variable?

It could be declared as DOWNLOADS="~/Downloads" and still work for those that keep their brunch releases and recovery images in `~/Downloads`. I have been keeping historical releases in `/usr/local/brunch-work` so with a DOWNLOADS variable I could just redefine it to work on my device instead of copying or moving everything to `~/Downloads`.

I may be the only one that doesn't keep their brunch stuff in `~/Downloads` so I'll understand if you don't want to do this, just thought I'd ask though.

Thanx,
-**DennisLfromGA**

**Comment by WesBosch** [comment]
I think it's a good idea actually. It would still be compatible with users
as it is while providing more flexibility to more experienced users. It
also goes hand in hand with a change I have been mulling over so I'll keep
a note of it going forward

**Comment by DennisLfromGA** [comment]
That's awesome, thanx for your quick response & kind consideration.

**Comment by WesBosch** [comment]
Alright, I've got a $DOWNLOADS variable working. It's currently set up like this:

DOWNLOADS="$HOME/Downloads"

which appears to work well in my testing. It's near the top of the script for easy changing (line 5) of the script in this zip file I've prepared for you. Would you be able to test this to see if it will work for your uses? If you have any changes or suggestions be sure to let me know


[brunch-toolkit-v1.0.2b.zip](https://github.com/WesBosch/brunch-toolkit/files/5382955/brunch-toolkit-v1.0.2b.zip)

**Comment by DennisLfromGA** [comment]
I'll grab my brunch device today, test it, and get back to you.

Thanx for accommodating this request - and *all* your efforts.
