### ISSUE TITLE
Problem choice of hdd

### ISSUE THREAD

**Issue by NR-The-Void** [WesBosch/brunch-toolkit#4]
Hello WesBosch

I don't know anything about Linux. 
your script helped me a lot.
But when it comes to choosing a hard drive, Mine does not appear, because I don't have HDD or SSD but an [M2 MVNE](https://www.kingston.com/unitedstates/en/community/articledetail/articleid/48543) 

M2 mvne is not : /sda /sdb /sdc.  But is /mvne0n1p1 /mvne0n1p2 /mvne0n1p3
![20210209_013320](https://user-images.githubusercontent.com/78773579/107310054-e7fc4480-6a8b-11eb-80c2-aa7eba5235de.jpg)

I looked everywhere impossible to find the solution

I need help ty

**Comment by WesBosch** [comment]
Ah, I did not realize that nvme used its own naming for drives, I'll be sure to remember this moving forward. Thank you for bringing it to my attention. 

For now, I suggest following the official brunch github guide until I can fix this. Your disk name for the official install script would be /dev/mvne0n

**Comment by WesBosch** [comment]
You may also test with this version. I'm not 100% sure if this will fix it as I dont have one of those disks to test it myself

[brunch-toolkit-v1.0.7b.zip](https://github.com/WesBosch/brunch-toolkit/files/5948581/brunch-toolkit-v1.0.7b.zip)

**Comment by NR-The-Void** [comment]
Thx for fast reply .
Thank you very much I will test this during the day and I will keep you informed.

**Comment by NR-The-Void** [comment]
Tyyyy, Nice job thx 

![20210209_085849](https://user-images.githubusercontent.com/78773579/107333438-c57f2100-6ab5-11eb-883b-fc998523e0fc.jpg)

**Comment by WesBosch** [comment]
Thanks for confirming that this worked! I'll post this as a new release and mark this topic as closed
