### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by da0ist** [WesBosch/brunch-toolkit#6]
This has been happening the past 24 hours or so:

chronos@localhost / $ brunch-toolkit 
/usr/local/bin/brunch-toolkit: line 1554: syntax error near unexpected token `('
/usr/local/bin/brunch-toolkit: line 1554: `            echo "If it is not a recognized option, you will be warned (it will still be added)"'

**Comment by WesBosch** [comment]
I'm not really sure what's causing this error, this line has not been
changed for several releases and it's just an echo command. I'll try to
look into it tonight, for now please use an older release from the releases page, or follow the normal brunch installation instructions

**Comment by WesBosch** [comment]
I've taken a look and I think I've fixed the issue, can you try the latest release to see if this has been fixed for you as well?
