### ISSUE TITLE
Chome OS startup animation

### ISSUE THREAD

**Issue by dtadptvl** [WesBosch/brunch-toolkit#8]
I'm a noob. I haven't install Chrome OS via Brunch and now I'm struggling to adjust the startup animation as it keeps showing Load Brunch Framework. I know your tool can help but I dont really know how to use it. Please help

**Comment by WesBosch** [comment]
It sounds like you aren't far enough into the installation process to do this yet. Are you able to get past the "Loading Brunch Framework" screen and log in?

**Comment by dtadptvl** [comment]
Sorry for typo. I mean my installation works fine, the only thing that I would like to change or get rid of is the screen that shows “Loading Brunch Framework”. Is it possible?

**Comment by WesBosch** [comment]
Oh, that is actually not the ChromeOS Boot Animation, it is the Brunch Bootsplash. You'll find the settings for that in the Grub Options menu under the Brunch Bootsplash submenu.

This menu option is only avaliable to singleboot users currently.

**Comment by dtadptvl** [comment]
Guess I have to get used to it. Thank you very much
